-- 既存のテーブルを削除
DROP TABLE IF EXISTS Book_Register;
DROP TABLE IF EXISTS Book_Info;
DROP TABLE IF EXISTS User_Info;

-- ユーザー情報テーブル
CREATE TABLE User_Info (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Gender VARCHAR(10),
    Age INT,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 本情報テーブル
CREATE TABLE Book_Info (
    Book_ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255),
    ReleaseDate DATE,
    Synopsis TEXT,
    Star INT CHECK (Star BETWEEN 1 AND 5),
    CreateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


-- 本登録テーブル
CREATE TABLE Book_Register (
    User_ID INT,
    Book_ID INT,
    BeforeReview TEXT,
    CreateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (User_ID, Book_ID),
    FOREIGN KEY (User_ID) REFERENCES User_Info(User_ID),
    FOREIGN KEY (Book_ID) REFERENCES Book_Info(Book_ID)
);
